version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Monitoring.Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=testsrv;Database=DocumentControl;User ID=sa;Password=Ahernar1985;TrustServerCertificate=True;
    networks:
      - monitoring_network
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Monitoring.UI/Dockerfile
    ports:
      - "3000:80"
    networks:
      - monitoring_network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Ahernar1985
    ports:
      - "1433:1433"
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge